# Binary Classification

In [ ]:
# step 1: import library
import pandas as pd
import numpy as np

In [ ]:
# step 2: import data
diabetes = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [ ]:
diabetes.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [ ]:
# step 3: define y and X

In [ ]:
y = diabetes['diabetes']
X = diabetes.drop(['diabetes'],axis=1)

In [ ]:
X.shape

(768, 8)

In [ ]:
# step 4: split data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# step 5: standardize
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [ ]:
X_train = ss.fit_transform(X_train)

In [ ]:
X_test = ss.transform(X_test)

In [ ]:
# step 6: model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [ ]:
model.add(Dense(9,activation= 'relu'))

In [ ]:
model.add(Dense(16,activation= 'relu'))

In [ ]:
model.add(Dense(16,activation= 'relu'))

In [ ]:
model.add(Dense(8 ,activation= 'relu'))

In [ ]:
model.add(Dense(1,activation= 'sigmoid'))

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy']    )

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=20,verbose=1)

Epoch 1/20
18/18 [==============================] - 1s 2ms/step - loss: 0.6795 - accuracy: 0.5417
Epoch 2/20
18/18 [==============================] - 0s 2ms/step - loss: 0.6559 - accuracy: 0.6910
Epoch 3/20
18/18 [==============================] - 0s 2ms/step - loss: 0.6258 - accuracy: 0.7135
Epoch 4/20
18/18 [==============================] - 0s 2ms/step - loss: 0.5906 - accuracy: 0.7188
Epoch 5/20
18/18 [==============================] - 0s 2ms/step - loss: 0.5570 - accuracy: 0.7500
Epoch 6/20
18/18 [==============================] - 0s 2ms/step - loss: 0.5297 - accuracy: 0.7639
Epoch 7/20
18/18 [==============================] - 0s 2ms/step - loss: 0.5060 - accuracy: 0.7691
Epoch 8/20
18/18 [==============================] - 0s 2ms/step - loss: 0.4894 - accuracy: 0.7639
Epoch 9/20
18/18 [==============================] - 0s 2ms/step - loss: 0.4773 - accuracy: 0.7656
Epoch 10/20
18/18 [==============================] - 0s 2ms/step - loss: 0.4697 - accuracy: 0.7656
Epoch 11/20
18/18 [

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (32, 9)                   81        
                                                                 
 dense_1 (Dense)             (32, 16)                  160       
                                                                 
 dense_2 (Dense)             (32, 16)                  272       
                                                                 
 dense_3 (Dense)             (32, 8)                   136       
                                                                 
 dense_4 (Dense)             (32, 1)                   9         
                                                                 
Total params: 658
Trainable params: 658
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# prediction
y_pred = model.predict(X_test)

6/6 [==============================] - 0s 2ms/step


In [ ]:
y_pred = np.round(y_pred)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[105,  13],
       [ 32,  42]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.89      0.82       118
           1       0.76      0.57      0.65        74

    accuracy                           0.77       192
   macro avg       0.77      0.73      0.74       192
weighted avg       0.77      0.77      0.76       192



# Multiclass problem

In [ ]:
# step 1: import library
import pandas as pd
import numpy as np

In [ ]:
# step 2: import data
iris = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/IRIS.csv')

In [ ]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# step 3: define y and X

In [ ]:
y = iris[['species']]
X = iris.drop(['species'],axis=1)

In [ ]:
X.shape, y.shape

((150, 4), (150, 1))

In [ ]:
# step convert y into dummy variable
y=pd.get_dummies(y)
y

species_Iris-setosa  species_Iris-versicolor  species_Iris-virginica
0                      1                        0                       0
1                      1                        0                       0
2                      1                        0                       0
3                      1                        0                       0
4                      1                        0                       0
..                   ...                      ...                     ...
145                    0                        0                       1
146                    0                        0                       1
147                    0                        0                       1
148                    0                        0                       1
149                    0                        0                       1

[150 rows x 3 columns]

In [ ]:
# step 4: split data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# step 5: standardize
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [ ]:
X_train = ss.fit_transform(X_train)

In [ ]:
X_test = ss.transform(X_test)

In [ ]:
# step 6: model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [ ]:
model.add(Dense(9,activation= 'relu'))

In [ ]:
model.add(Dense(16,activation= 'relu'))

In [ ]:
model.add(Dense(16,activation= 'relu'))

In [ ]:
model.add(Dense(8 ,activation= 'relu'))

In [ ]:
model.add(Dense(3,activation= 'softmax'))

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy']    )

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=20,verbose=1)

Epoch 1/20
4/4 [==============================] - 1s 3ms/step - loss: 1.2440 - accuracy: 0.2232
Epoch 2/20
4/4 [==============================] - 0s 3ms/step - loss: 1.2028 - accuracy: 0.2321
Epoch 3/20
4/4 [==============================] - 0s 3ms/step - loss: 1.1665 - accuracy: 0.2500
Epoch 4/20
4/4 [==============================] - 0s 3ms/step - loss: 1.1352 - accuracy: 0.3393
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 1.1070 - accuracy: 0.4375
Epoch 6/20
4/4 [==============================] - 0s 3ms/step - loss: 1.0821 - accuracy: 0.5179
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 1.0583 - accuracy: 0.5625
Epoch 8/20
4/4 [==============================] - 0s 3ms/step - loss: 1.0352 - accuracy: 0.6161
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0130 - accuracy: 0.6518
Epoch 10/20
4/4 [==============================] - 0s 3ms/step - loss: 0.9900 - accuracy: 0.6786
Epoch 11/20
4/4 [======================

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 9)                 45        
                                                                 
 dense_6 (Dense)             (None, 16)                160       
                                                                 
 dense_7 (Dense)             (None, 16)                272       
                                                                 
 dense_8 (Dense)             (None, 8)                 136       
                                                                 
 dense_9 (Dense)             (None, 3)                 27        
                                                                 
Total params: 640
Trainable params: 640
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# prediction
y_pred = model.predict(X_test)

2/2 [==============================] - 0s 3ms/step


In [ ]:
y_pred

array([[0.85496444, 0.07189173, 0.0731438 ],
       [0.7531097 , 0.12361167, 0.12327859],
       [0.76743627, 0.12189992, 0.11066382],
       [0.19338173, 0.49874315, 0.3078752 ],
       [0.1923384 , 0.5014726 , 0.30618894],
       [0.25775203, 0.4322463 , 0.31000167],
       [0.21660505, 0.47613192, 0.30726308],
       [0.2522039 , 0.42788985, 0.3199062 ],
       [0.2058819 , 0.48119968, 0.31291857],
       [0.2299148 , 0.45322007, 0.31686515],
       [0.2396668 , 0.43877503, 0.3215582 ],
       [0.23840676, 0.43811458, 0.32347867],
       [0.23235635, 0.45869413, 0.30894947],
       [0.20627499, 0.50562644, 0.28809854],
       [0.8724055 , 0.06294835, 0.06464622],
       [0.22743595, 0.45352322, 0.31904078],
       [0.24967101, 0.42766675, 0.32266223],
       [0.20196094, 0.48727322, 0.3107658 ],
       [0.80760825, 0.09586031, 0.09653145],
       [0.8318232 , 0.08156703, 0.0866097 ],
       [0.8146661 , 0.08946141, 0.09587253],
       [0.8318232 , 0.08156703, 0.0866097 ],
       [0.

In [ ]:
np.argmax(y_pred,axis=1)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [ ]:
y_pred=np.argmax(y_pred,axis=1)

In [ ]:
np.argmax(y_test.values,axis=1)

array([0, 0, 0, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 0, 0, 0,
       2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 1, 0])

In [ ]:
y_test=np.argmax(y_test.values,axis=1)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0, 19,  0]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.24      1.00      0.39         6
           2       0.00      0.00      0.00        19

    accuracy                           0.50        38
   macro avg       0.41      0.67      0.46        38
weighted avg       0.38      0.50      0.40        38



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Regression

In [ ]:
# step 1: import library
import pandas as pd
import numpy as np

In [ ]:
# step 2: import data
house = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Boston.csv')

In [ ]:
house.head()

CRIM    ZN  INDUS  CHAS     NX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [ ]:
# step 3: define y and X

In [ ]:
y = house['MEDV']
X = house.drop(['MEDV'],axis=1)

In [ ]:
X.shape

(506, 13)

In [ ]:
# step 4: split data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# step 5: standardize
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [ ]:
X_train = ss.fit_transform(X_train)

In [ ]:
X_test = ss.transform(X_test)

In [ ]:
# step 6: model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [ ]:
model.add(Dense(14,activation= 'relu'))

In [ ]:
model.add(Dense(28,activation= 'relu'))

In [ ]:
model.add(Dense(28,activation= 'relu'))

In [ ]:
model.add(Dense(13,activation= 'relu'))

In [ ]:
model.add(Dense(1,activation= 'linear'))

In [ ]:
model.compile(optimizer='adam',loss='mean_absolute_error', metrics=['mean_absolute_error']    )

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=200,verbose=1)

Epoch 1/200
12/12 [==============================] - 0s 2ms/step - loss: 3.3344 - mean_absolute_error: 3.3344
Epoch 2/200
12/12 [==============================] - 0s 2ms/step - loss: 3.2527 - mean_absolute_error: 3.2527
Epoch 3/200
12/12 [==============================] - 0s 2ms/step - loss: 3.2167 - mean_absolute_error: 3.2167
Epoch 4/200
12/12 [==============================] - 0s 2ms/step - loss: 3.1579 - mean_absolute_error: 3.1579
Epoch 5/200
12/12 [==============================] - 0s 2ms/step - loss: 3.1325 - mean_absolute_error: 3.1325
Epoch 6/200
12/12 [==============================] - 0s 3ms/step - loss: 3.1073 - mean_absolute_error: 3.1073
Epoch 7/200
12/12 [==============================] - 0s 2ms/step - loss: 3.0779 - mean_absolute_error: 3.0779
Epoch 8/200
12/12 [==============================] - 0s 2ms/step - loss: 3.0090 - mean_absolute_error: 3.0090
Epoch 9/200
12/12 [==============================] - 0s 2ms/step - loss: 2.9605 - mean_absolute_error: 2.9605
Epoch 10/2

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 14)                196       
                                                                 
 dense_11 (Dense)            (None, 28)                420       
                                                                 
 dense_12 (Dense)            (None, 28)                812       
                                                                 
 dense_13 (Dense)            (None, 13)                377       
                                                                 
 dense_14 (Dense)            (None, 1)                 14        
                                                                 
Total params: 1,819
Trainable params: 1,819
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# prediction
y_pred = model.predict(X_test)

4/4 [==============================] - 0s 2ms/step


In [ ]:
y_pred

array([[31.601482 ],
       [20.959387 ],
       [19.652414 ],
       [46.917244 ],
       [19.207268 ],
       [22.525768 ],
       [16.509651 ],
       [15.103347 ],
       [21.385403 ],
       [19.970936 ],
       [18.287376 ],
       [23.200504 ],
       [28.87777  ],
       [14.071507 ],
       [11.494173 ],
       [23.796936 ],
       [19.416111 ],
       [21.464495 ],
       [11.201558 ],
       [38.570255 ],
       [21.421394 ],
       [16.277695 ],
       [14.233689 ],
       [21.441814 ],
       [24.873898 ],
       [20.910288 ],
       [19.657581 ],
       [18.9327   ],
       [25.032911 ],
       [23.539766 ],
       [16.159243 ],
       [15.807106 ],
       [22.299408 ],
       [22.352072 ],
       [43.796623 ],
       [23.251034 ],
       [47.565456 ],
       [23.050735 ],
       [38.334064 ],
       [15.301497 ],
       [14.472419 ],
       [23.031229 ],
       [ 8.509817 ],
       [12.077905 ],
       [19.312433 ],
       [35.88022  ],
       [17.967794 ],
       [15.34

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

0.11704543910494826